#!/bin/bash

cf delete accounts -f
cf delete quotes -f
cf delete portfolio -f
cf delete webtrader -f

cf delete config-server -f
cf delete discovery-service -f
cf delete circuit-breaker-dashboard -f

cf delete-service config-server -f
cf delete-service discovery-service -f
cf delete-service circuit-breaker-dashboard -f
cf delete-service traderdb -f
